FROM ubuntu:bionic
  
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Install prerequisites
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        curl \
        git \
        libbz2-dev \
        libffi-dev \
        liblzma-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        llvm \
        make \
        python-openssl \
        python3-pip \
        tk-dev \
        vim \
        wget \
        xz-utils \
        zlib1g-dev \
    && apt-get install -y \
        cmake \
        libhdf5-dev \
        libnexus0-dev \
        python3-numpy \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://pyenv.run | bash
RUN pyenv install 2.7.16 \
    && pyenv install 3.5.7 \
    && pyenv install 3.6.9 \
    && pyenv install 3.7.4 \
    && pyenv global 3.6.9 3.7.4 3.5.7 2.7.16 \
    && pip3 install pipenv tox flake8 pytest pytest-cov

# Install nexusformat
RUN git clone https://github.com/nexusformat/code.git nexusformat \
    && cd nexusformat \
    && mkdir build \
    && cd build \
    && cmake -DENABLE_APPS=ON -DENABLE_CXX=ON .. \
    && make \
    && make install

# Install python-nxs
RUN git clone https://github.com/jkrueger1/python-nxs.git \
    && cd python-nxs \
    && python3 setup.py install

# Add test file
RUN wget -O /app/test_event_file.nxs http://${MANTID_FTP_SERVER}/ftp/external-data/MD5/${EVENT_FILE_MD5}

WORKDIR /app
COPY . /app
CMD ["python3", "/app/shrinkeventfile"]
